### ISSUE TITLE
Improve top section of the README

### ISSUE THREAD

**Issue by flenter** [autometrics-dev/autometrics-py#24]
Add some links out similar to what the rust flavor of the library does:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/473804/233363193-ed050f12-1148-49e6-8e5f-ba03b4eab290.png">

i.e. Link to pypi, discord and hopefully in the future: a docs website

**Comment by actualwitch** [comment]
i added ci badge from github, we should figure out the "publish to readthedocs" story and that's probably last shield we want there
