### ISSUE TITLE
Add support for adding version/commit information to metrics

### ISSUE THREAD

**Issue by flenter** [autometrics-dev/autometrics-py#25]
Similar to: https://github.com/autometrics-dev/autometrics-rs/pull/69

**Comment by brettimus** [comment]
OTEL support is blocked by https://github.com/open-telemetry/opentelemetry-python/issues/3071

I've submitted a PR to resolve it here:
https://github.com/open-telemetry/opentelemetry-python/pull/3306

**Comment by brettimus** [comment]
closing this and will file a separate bug for OTEL support
