### ISSUE TITLE
Add support for async functions

### ISSUE THREAD

**Issue by flenter** [autometrics-dev/autometrics-py#29]
Right now the decorator assumes that the function it is wrapping when it returns it is also finished. This is not the case with async functions.

``` python
async def async_function():
    """This is an async function."""
    await asyncio.sleep(0.1)
    return True
```

When calling this function it will return quickly but when you use `await` it suddenly takes ~0.1s longer.

**Comment by brettimus** [comment]
Adding a note here: Decorating fastapi path operation functions with @autometrics breaks the API


So, this throws an error:
```py
@app.get("/async-test")
@autometrics
async def async_test_route():
    message = await my_async_function()
    return {"Hello": message}
```


But this works:
```py
@app.get("/async-test")
async def async_test_route():
    message = await my_async_function()
    return {"Hello": message}
```
