### ISSUE TITLE
build_info metric does not work with OpenTelemetry tracker

### ISSUE THREAD

**Issue by brettimus** [autometrics-dev/autometrics-py#38]
We will need to wait for an upstream fix to the opentelemetry-python project's prometheus metric reader.

There is an open PR to fix this in the opentelemetry-python repo: https://github.com/open-telemetry/opentelemetry-python/pull/3306

**Comment by brettimus** [comment]
that's a fair point. what seems to happen though is no `build_info` metric is defined. only `build_info_total`


<img width="962" alt="image" src="https://github.com/autometrics-dev/autometrics-py/assets/3201327/f5df827c-a459-4cd7-aeb0-3f0c3846cd4d">


<img width="1403" alt="image" src="https://github.com/autometrics-dev/autometrics-py/assets/3201327/f79806c8-6a9b-4281-9a45-2091a0b4a372">

**Comment by emschwartz** [comment]
Ah, oh course. That's annoying

**Comment by brettimus** [comment]
opentelemetry-python v1.20 includes the fix for this! i will open a PR that mentions this in the README (that versions before that do not work with build info)

**Comment by brettimus** [comment]
closed with #92
