### ISSUE TITLE
Investigate: Get qualified name for function so autometrics does not need to be the topmost decorator

### ISSUE THREAD

**Issue by brettimus** [autometrics-dev/autometrics-py#56]
In the README, we write:

> Autometrics by default will try to store information on which function calls a decorated function. As such you may want to place the autometrics in the top/first decorator, as otherwise you may get inner or wrapper as the caller function.

It would be nice to implement our decorator so that it does not rely on being the topmost decorator above a function.

This should be possible. For reference, check out the [utility function used by Sentry in their SDK's decorators](https://github.com/getsentry/sentry-python/blob/c26f35a248bb2400f547f1d0ecb957b961f35563/sentry_sdk/utils.py#L1220)

**Comment by actualwitch** [comment]
resolved in https://github.com/autometrics-dev/autometrics-py/pull/59
