### ISSUE TITLE
Automatically serve `/metrics` on port 9464

### ISSUE THREAD

**Issue by brettimus** [autometrics-dev/autometrics-py#69]
From the Typescript docs:

> By default the TypeScript library makes the metrics available on <your_host>:9464/metrics. Make sure your Prometheus is configured correctly to find it.

autometrics-py should do something similar!

**Comment by actualwitch** [comment]
i think there's still no decision on how to standardize it
https://github.com/orgs/autometrics-dev/discussions/32
