### ISSUE TITLE
allow newer prometheus client  versions

### ISSUE THREAD

**Issue by cristifalcas** [autometrics-dev/autometrics-py#71]
Any reason to force the version of prometheus client to 0.16?
```
prometheus-client = "0.16.0"
```
This blocks us from trying out the module, since we have in our projects 0.17 setup already.

**Comment by actualwitch** [comment]
Hello @cristifalcas! Thank you for checking out autometrics, we'd love to hear what you think about it!
We don't have any specific reason to stay on 0.16, we'll bump it in the next release.

**Comment by brettimus** [comment]
alright! @cristifalcas we just cut a new version of autometrics, `0.8`, which should work with 0.17.0 and 0.17.1 of `prometheus-client` 

let us know how it goes trying out

**Comment by cristifalcas** [comment]
thanks, I'll give it a try
