### ISSUE TITLE
Ruby language support

### ISSUE THREAD

**Issue by kingsleyh** [autometrics-dev/autometrics-py#95]
Would it be hard to add support for Ruby? I see Python is supported - maybe it would be similar to that one? maybe could be contributed if not too hard to add.

**Comment by brettimus** [comment]
hey! i started work for this back in february, but after visiting some meetups and talking to a few teams, i didn't see much demand and stopped developing it.

also a big blocker for me was how difficult the dev tooling was proving to be (getting tooltips in vscode)

the repo is here if you wanna take a peak: https://github.com/autometrics-dev/autometrics-rb

then, i tried writing a solargraph plugin (https://github.com/autometrics-dev/solargraph-autometrics) for the tooltips, but i hit an issue with that language server's plugins

https://github.com/castwide/solargraph/issues/636

**Comment by brettimus** [comment]
if you wanna take a crack at ruby, i'd be happy to sync sometime

**Comment by brettimus** [comment]
hey! just saw you posted this as a discussion too. i'm going to move my response there and close this, hope that's alright
